"""add embedding source hash

Revision ID: 0bf709c1a2fd
Revises: 0e10f7252648
Create Date: 2026-07-15 07:04:06.807605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf709c1a2fd'
down_revision: Union[str, Sequence[str], None] = '0e10f7252648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_stones', sa.Column('embedding_source_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_stones', 'embedding_source_hash')
    # ### end Alembic commands ###
