"""add memory stone embeddings

Revision ID: 0e10f7252648
Revises: d53da8127c19
Create Date: 2026-07-14 16:07:48.807059

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e10f7252648'
down_revision: Union[str, Sequence[str], None] = 'd53da8127c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_stones', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('memory_stones', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('memory_stones', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_stones', 'embedded_at')
    op.drop_column('memory_stones', 'embedding_model')
    op.drop_column('memory_stones', 'embedding')
    # ### end Alembic commands ###
