"""add person aliases

Revision ID: 3973a4915651
Revises: 0bf709c1a2fd
Create Date: 2026-07-15 14:33:26.600075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3973a4915651'
down_revision: Union[str, Sequence[str], None] = '0bf709c1a2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalized_alias', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', name='uq_person_aliases_normalized_alias')
    )
    op.create_index(op.f('ix_person_aliases_normalized_alias'), 'person_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_person_aliases_person_id'), 'person_aliases', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_aliases_person_id'), table_name='person_aliases')
    op.drop_index(op.f('ix_person_aliases_normalized_alias'), table_name='person_aliases')
    op.drop_table('person_aliases')
    # ### end Alembic commands ###
