"""add memory stone provenance fields

Revision ID: 6b3af51e70c0
Revises: 9792bfcf6104
Create Date: 2026-07-14 14:23:06.324057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3af51e70c0'
down_revision: Union[str, Sequence[str], None] = '9792bfcf6104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_stones', sa.Column('source_type', sa.String(length=50), server_default=sa.text("'user_entry'"), nullable=False))
    op.add_column('memory_stones', sa.Column('source_reference', sa.Text(), nullable=True))
    op.add_column('memory_stones', sa.Column('remembered_at', sa.Date(), nullable=True))
    op.add_column('memory_stones', sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default=sa.text('1.000'), nullable=False))
    op.add_column('memory_stones', sa.Column('is_inferred', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_stones', 'is_inferred')
    op.drop_column('memory_stones', 'confidence')
    op.drop_column('memory_stones', 'remembered_at')
    op.drop_column('memory_stones', 'source_reference')
    op.drop_column('memory_stones', 'source_type')
    # ### end Alembic commands ###
