"""add people and memory relationships

Revision ID: 92d583f8b0da
Revises: 6b3af51e70c0
Create Date: 2026-07-14 14:32:10.951999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d583f8b0da'
down_revision: Union[str, Sequence[str], None] = '6b3af51e70c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_stone_people',
    sa.Column('memory_stone_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), server_default=sa.text("'mentioned'"), nullable=False),
    sa.ForeignKeyConstraint(['memory_stone_id'], ['memory_stones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_stone_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_stone_people')
    op.drop_table('people')
    # ### end Alembic commands ###
