"""add memory source text hash

Revision ID: c0f95341a520
Revises: 3973a4915651
Create Date: 2026-07-16 10:07:42.769513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f95341a520'
down_revision: Union[str, Sequence[str], None] = '3973a4915651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_stones', sa.Column('source_text_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_memory_stones_source_text_hash'), 'memory_stones', ['source_text_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_stones_source_text_hash'), table_name='memory_stones')
    op.drop_column('memory_stones', 'source_text_hash')
    # ### end Alembic commands ###
