"""add memory importance

Revision ID: f0cf9bc50d7d
Revises: c0f95341a520
Create Date: 2026-07-16 12:35:04.255424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cf9bc50d7d'
down_revision: Union[str, Sequence[str], None] = 'c0f95341a520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_stones', sa.Column('importance', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.500'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_stones', 'importance')
    # ### end Alembic commands ###
